spring.application.name=backend


spring.datasource.url=jdbc:mysql://localhost:3306/bankdb
spring.datasource.username=root
spring.datasource.password=J110103.r1103

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=uWeuM5g048KB4SY8kugd+n2BHToukvvL7au2Vd0wU+U=
jwt.expiration=360000