spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/bankdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true

jwt.secret=uWeuM5g048KB4SY8kugd+n2BHToukvvL7au2Vd0wU+U=
jwt.expiration=3600000

aes.secret-key=x2rRHwxq+YkBfiNT3kB+76ozrYkBcdx+el3t4G60lyc=

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a684f2001@smtp-brevo.com
spring.mail.password=xsmtpsib-14b6436581f0ab7641370b03781e4b843a41b09eaaf3bd57411f216b95eeff45-gDMwF4JgOuBYfNCe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

brevo.sender.email=sovereignledger01@gmail.com
brevo.sender.name=Sovereign Ledger

otp.expiration.minutes=5
otp.max.attempts=3
otp.resend.cooldown.minutes=1
